<?php

return [
    'VEDITOR' => env('VEDITOR', 'AUTO'),
    'VEDITOR_FOLDER_VIEWS_PATH' => env('VEDITOR_FOLDER_VIEWS_PATH', null),
    'VEDITOR_URL' => env('VEDITOR_URL', 'bblstudio'),
    'VEDITOR_ROUTE_NAME' => env('VEDITOR_ROUTE_NAME', 'bblstudio'),
    'VEDITOR_SAVE' => env('VEDITOR_SAVE', 'origin'),
    'VEDITOR_SAVE_DATA_FUN_CONTROLLER_NAME' => env('VEDITOR_SAVE_DATA_FUN_CONTROLLER_NAME',),
    'VEDITOR_SAVE_DATA_FUN_METHOD_NAME' => env('VEDITOR_SAVE_DATA_FUN_METHOD_NAME',),
    'VEDITOR_GET_CONTENT_BY_NAME_CONTROLLER_NAME' => env('VEDITOR_GET_CONTENT_BY_NAME_CONTROLLER_NAME',),
    'VEDITOR_GET_CONTENT_BY_NAME_METHOD_NAME' => env('VEDITOR_GET_CONTENT_BY_NAME_METHOD_NAME',),
    'VEDITOR_LIST_STRUCTER_CONTROLLER_NAME' => env('VEDITOR_LIST_STRUCTER_CONTROLLER_NAME',),
    'VEDITOR_LIST_STRUCTER_METHOD_NAME' => env('VEDITOR_LIST_STRUCTER_METHOD_NAME',),
    'VEDITOR_SHOW_PHP'=>env('VEDITOR_SHOW_PHP',true),
    'VEDITOR_MIDDLEWARE_ALIAS'=>env('VEDITOR_MIDDLEWARE_ALIAS',null)
];
